### ISSUE TITLE
Feature Request : Consider adding the app in F-Droid

### ISSUE THREAD

**Issue by Chidhambararajan** [BasicAirData/GPSLogger#123] opened 2020-12-11 10:49 UTC
Since the app is opensource , your app will get a lot of interest in F-Droid community
There are very few apps currently present in F-Droid which offers the same functionality

Just a suggestion

**Comment by Chidhambararajan** [comment] 2020-12-11 10:50
Consider adding walking / trecking / jogging tracking feautres too

**Comment by GrazianoCapelli** [comment] 2020-12-11 13:00
It is a duplicate of issue #8

**Closed by GrazianoCapelli** 2020-12-11 13:00 UTC
