### ISSUE TITLE
Recommend EGM2008

### ISSUE THREAD

**Issue by mikeglee** [BasicAirData/GPSLogger#220] opened 2024-05-26 15:41 UTC
I would encourage you to go all out and implement EGM2008. It's what iPhones use, and it would be great for Android devices to be able to achieve the same level of accuracy.

 https://developer.apple.com/documentation/corelocation/cllocation/1423820-altitude

**Comment by GrazianoCapelli** [comment] 2024-05-26 20:53
I close this issue because it is a duplicate of the issue #149
Anyway, thanks for the suggestion!

**Closed by GrazianoCapelli** 2024-05-26 20:53 UTC
