### ISSUE TITLE
App needs to run in background

### ISSUE THREAD

**Issue by orbiterFan** [BasicAirData/GPSLogger#205] opened 2023-02-05 09:28 UTC
Hi Guys

Really cool app. I am on a 1500km canoe journey right now, third week in, and when my phone is in ultrasaver, I run your app, but switch to camera a lot.

After a while your app stop logging. Please can you fix this.

This is a real world case where gpslogging should continue.

I am canoeing 5 Rivers, and the other thing that would be useful is more intervals, like 5 second and 10 second, that is useful for the waterways. My average speed is 1.5km/h. Yeah I know. Very slow.

Your app works well, but needs to run no matter what other app is in the foreground.

Thanks for the great work. Interface is a beaut.

Check out the unfolding journey right now. https://m.youtube.com/channel/UCwR7NmYONAAq6me4ZbeXkNQ

**Comment by GrazianoCapelli** [comment] 2023-02-06 22:17
> I am canoeing 5 Rivers, and the other thing that would be useful is more intervals, like 5 second and 10 second, that is useful for the waterways. My average speed is 1.5km/h. Yeah I know. Very slow.

If you want to log a point every 10 seconds, you should leave the GPS update interval to 1 second (to keep a good GPS accuracy) and set an interval filter of 10 seconds.

As alternative, if you would for example to record a point every 5 meters, you can set a Distance Filter of 5 meters.

**Comment by orbiterFan** [comment] 2023-02-13 16:58
Thanks for the help. I will try the filter. I have also switched to OpenCamera on fdroid.

**Comment by GrazianoCapelli** [comment] 2023-03-22 09:20
@orbiterFan - I close this issue, to keep our issue tracker clean.
Feel free to comment or re-open the issue in case of need.

If possible, We would be glad to know if the problem is still present also using OpenCamera.

**Closed by GrazianoCapelli** 2023-03-22 09:20 UTC
