### ISSUE TITLE
Design and implementation of a new Bottom Bar

### ISSUE THREAD

**Issue by electronoob** [BasicAirData/GPSLogger#88] opened 2020-08-01 16:43 UTC
Seems to me, and confirmed by one friend, that the ui is counter-intuitive in regards to someone just wanting to log their journey for the first time.

You know, and I know, how to begin logging; my friend though managed to log nothing today and was a bit disappointed by it. instead of having to explain to every person who might want to use it, perhaps a 'click here to start logging' followed by 'click here to stop logging' would be wonderful. The current interface for it is clear, inteligent and makes complete sense - but maybe for technically inclined minds and not quite so much for casual users.

otherwise I'm happy personally, left a nice shining review and begun thinking of ways to include this software into my workflow so i can archive and review previous trips.

cheers :)

**Comment by GrazianoCapelli** [comment] 2020-08-18 08:00
@electronoob First of all thanks for your time end for your feedback.

The issue you are reporting is true and confirmed over time by other users.
In effect it seems that the bottom bar is not intuitive for some first time users.

For quite some time I'm looking at other bottom bar UIs and I started to think of a new bottom bar for GPS Logger.
Furthermore, I'm thinking to take advantage of the opportunity to make some changes:
1) Remove the ugly "V tick" from the upper bar in favour of a more intuitive "Stop" (Finish) button on bottom bar
2) Add a "Lock" feature in order to avoid accidental clicks during the recording process
3) Prepare some additional space for other features

To date I only have an ugly draft of it:

![photo_2020-06-11_11-56-49_300x533](https://user-images.githubusercontent.com/6907566/90480204-3578a400-e130-11ea-9839-e2fedc130e92.jpg)

I didn't publish this draft yet because I'm not convinced about it (I'm not sure this implementation can be a step towards intuitiveness), and because I'm experimenting a lot on icons and positions.

As requirements, I would to keep the number of points and placemarks on the new bottom bar: users found it a very useful information. Furthermore, thinking on the UI, I chosen to consider that the new bottom bar should modify the user experience of the consolidated users as little as possible.

We apologise for the delayed answer, but the summer is vacation time for some contributors.
I suggest to keep the issue open: we could use it to collect and keep track of ideas, better UI mockups, suggestions, and in case to track the implementation status of the feature.

**Comment by ygoe** [comment] 2020-10-10 09:50
I can confirm that the UI is not intuitive. I found this app a few days ago for my new phone (the old app isn't available anymore) and tried it first yesterday. I didn't read any instructions and instead explored the UI the usual way.

The big info boxes on the main screen are misleading. They look like buttons, with their border and gradient background. In fact they're non-interactive. That style should be made more flat to avoid the interpretation of a pushable button. I'm not sure they need a border at all.

BTW, the display of the coordinates is... strange. "49:34:46,12345 N" is your invention, right? It's normally formatted as "49° 34′ 46,12345″ N". You can copy the degree, minute and second symbols from here, they're the typographically correct ones.

As long as there aren't any more values on the main screen, they'd be a lot easier to read if there were icons with the small label texts.

Then there's the bottom bar. It doesn't look interactive at all. There's just two more numbers with a label, this time in inverse order (label top). And the menu in the top right corner doesn't contain any actions. So I can't see immediately how to operate this thing.

Exploration phase 2 starts. I start tapping around. Main screen info boxes: no reaction. Other tabs: empty, no buttons. Well, let's try that bottom bar. After all, there has to be something hidden somewhere. Hit the left button, and it turned red. Nice. I am asked for a place name. Huh? Entered something and confirmed. But button isn't red anymore and the number stays at 1. Well, I'm standing still. Maybe it'll log positions when I start moving, but I can't look because I'm driving.

At the end of my short drive, the number was still at 1. The exported track had a single point. That looked very buggy now. Checked the background activity permission and corrected the battery optimisation setting. But it shouldn't have kicked in after a few minutes. And I don't really know the difference between "Ortsmarker" (place mark) and "Wegpunkte" (waypoints). To me, a track contains points. That's it.

Exploration complete, operation unclear. Then I found the tutorial. That made things a lot clearer. But you really force every app user to read this, probably often after a bad experience.

I believe this app can become useful and great, but there's a bit work to do. It already looks nice, clean and modern. I just believe that the UI toolkit isn't used appropriately to make the most of it.

I'd start by adding a big round "record" button on the main screen. Like in a voice recorder. My Samsung recorder app does this: There's a single red round record button in the centre. It makes absolutely clear that recording starts when I push it. When I do, it's replaced by two buttons (and others that don't apply here): A pause button in the place of the record button (to suspend recording) and a stop button next to it (to finish recording). Pressing the pause button replaces that with the record button again (to continue recording).

Here are the screenshots:

Initially:
![grafik](https://user-images.githubusercontent.com/868315/95651418-98603900-0aea-11eb-985a-a3fef6cfab80.png)

When recording:
![grafik](https://user-images.githubusercontent.com/868315/95651434-a910af00-0aea-11eb-8eeb-14ede8d3796e.png)

When paused:
![grafik](https://user-images.githubusercontent.com/868315/95651439-ae6df980-0aea-11eb-9bf3-5a288a80234f.png)

When stopping:
![grafik](https://user-images.githubusercontent.com/868315/95651445-b75ecb00-0aea-11eb-84e0-b7abb40d5462.png)

When pressing the back button if not saved:
![grafik](https://user-images.githubusercontent.com/868315/95651449-c180c980-0aea-11eb-9dad-2f81b14dd44a.png)

To the left, instead of the playback button, I could imagine the "save placemark" button, with a map pin icon and a cutout plus icon inside (not outlined). That would explicitly save a named place, asking for a name.

The voice recorder shows the current recording length somewhere at the top. The number of recorded GPS locations and saved place marks could be displayed in a separate row, too. Probably above the corresponding buttons. The main action buttons and counters would make the bottom bar.

If you wanted to lock the stop button against accidental use, you could again follow the voice recorder: When stopping, it asks for a track name. If pressing "Cancel", it stays in pause mode so you can easily resume recording. Alternatively, there could be a user setting that requires the stop button to be pressed for some time to trigger (1–2 seconds). If pressed too shortly, a toast message should give instructions how to stop ("Press longer to stop recording.").

I wouldn't outline the stop and record icons (as in your draft screenshot). They're best recognised if filled. And the red colour of the record button is important.

I'll still have to find out what the other two tabs are for, so I can't say anything about them now.

**Comment by ygoe** [comment] 2020-10-10 10:35
Haha, we already have a big red button! But only in the logo. ;-) The app UI might want to reflect that.

![Logo](https://lh3.googleusercontent.com/fUUrplUOZ7bJDPL1kgeEDshgu0cIbL3er7Ge8WAT1Rr7pKUKFRYsP4hg9f9Tqpthuw=s180)

**Comment by GrazianoCapelli** [comment] 2020-10-19 13:07
As a second iteration of my previous idea, I would to share the following image:

![New Bottom Bar - 20201013_s](https://user-images.githubusercontent.com/6907566/96454801-aca7e280-121c-11eb-97ff-9b87e84848ea.jpg)

We could choose to display the number of Placemark and Trackpoints when the amount is >0 instead of button Label.
The two numbers could be present in Track's tab as Tiles, but I suspect that the users are used to read these data on bottom bar in order to have an immediate feedback of the recording process.

The "Finish" button should be grayed out when the amount of Trackpoints+Placemarks is zero, because the track is empty.

Of course, any alternative (and completely different) mockup is welcome!

**Comment by GrazianoCapelli** [comment] 2020-10-19 13:22
@ygoe by the way, the possibility to specify a description when the user finalize a track is a very good idea.

**Comment by ygoe** [comment] 2020-10-21 20:49
I don't like the idea of hiding the labels after some (short) time and show progress information in their place. Labels explain the UI. Either you use them or you don't, but don't change midway. That takes away part of the orientation. I wouldn't expect the user to "learn" the UI (so that they won't need the labels anymore) in such a short time. And you usually only skip the labels entirely if the UI is clear enough. Couldn't those numbers be displayed in the middle area? I think the design of mixing progress with actions is a bit broken. Fixing this may need "breaking changes" in users' behaviour. They'll get used to it.

Disallowing to stop a recording if no data has been recorded yet could cause serious trouble. Imagine you start a recording, don't have reception and found it was a mistake. Now you want to undo. The only was is the stop button. Don't lock the way out in such a way. If I want to stop, I must be able to, or slight panic may start to develop. Anyway, what's the issue with stopping an empty recording? There's nothing wrong with that. It's a legal operation. It just has no effect. And as such, asking for a track name would probably be inappropriate then. ;-) Instead, a short message could inform the user that the empty recording wasn't saved.

**Comment by GrazianoCapelli** [comment] 2020-11-01 09:24
> Disallowing to stop a recording if no data has been recorded yet could cause serious trouble. Imagine you start a recording, don't have reception and found it was a mistake. Now you want to undo. The only was is the stop button. Don't lock the way out in such a way. If I want to stop, I must be able to, or slight panic may start to develop. Anyway, what's the issue with stopping an empty recording? There's nothing wrong with that. It's a legal operation. It just has no effect. And as such, asking for a track name would probably be inappropriate then. ;-) Instead, a short message could inform the user that the empty recording wasn't saved.

The more I think about it, the more I agree with you.

**Comment by GrazianoCapelli** [comment] 2021-04-11 18:16
This week I thought on how to implement the Bottom Bar without lose the information of the amount of Trackpoints and Placemarks recorded.
I tried a first implementation of it with the commit 642c9b9.
Currently only "Record" and "Annotate" works.
The "Stop" button will replace the ugly "V tick" on top (a single click will show a message with the possibility to add a description and change the track type), and the "Lock" button will lock the bottom bar to avoid unwanted clicks.

![photo_2021-04-11_18-44-14](https://user-images.githubusercontent.com/6907566/114315494-842fdf80-9aff-11eb-9ecb-6dd6625bcf64.jpg)

Not bad for me as first iteration.
If this feature will reach a good implementation level, it will be included into the App.
Time for comments and ideas!

**Comment by GrazianoCapelli** [comment] 2021-04-24 14:55
With the last commits we implemented the editing of the some track details (description and activity type).
The dialog is shown when the user clicks the **Stop** button on the bottom bar.
The description appears in the tracklist on the upper part of each card, where we reserved some space more than one year ago.
If the description field is left empty, the app shows the ID of the track like previously:

![Screenshot_20210424-1633_GPS Logger](https://user-images.githubusercontent.com/6907566/115962611-8db44100-a51c-11eb-9359-8d41860527ed.jpg)

I made some tests, the feature is stable enough to be merged into the develop branch.

It is possible to follow the implementation of the editing dialog for the old recorded tracks (the feature will be added to Tracklist's actionbar) - and the logic of the file names into /GPSLogger folders - by following the issue #47.

**Comment by GrazianoCapelli** [comment] 2021-04-24 16:28
Here I annotate a small list of related tasks that could/should be implemented in order to get the bottom bar better:
1) If the user clicks **Record** or **Annotate** when the app has not yet obtained a FIX, we could show a toast that warns that the points and the placemarks will start to be collected as soon as the app will find the GPS signal.
2) The **Stop** button should be enabled as soon as the user clicks **Record** or **Annotate**, also if no points are collected yet. The users (like @ygoe wrote) could be more comfortable with a stop button active. The reason of it is that, unlike a sound recorder, from the click of Record and the first FIX could pass a certain amount of time, and the users could feel disoriented without a **Stop** button.
3) If the **Stop** button is pressed when no points/annotation are recorded, the app should show a tooltip with a message like "Nothing to save".

**Comment by GrazianoCapelli** [comment] 2021-05-14 13:03
Here below a screenshot of the bottom bar that will be included into the v3.0.0:

![GPSLogger300_20210514](https://user-images.githubusercontent.com/6907566/118273827-b8167000-b4c4-11eb-8176-f4d6770db3c4.jpg)

(The screenshot shows the app in the middle of a recording).
Time for suggestions.

**Comment by Turdus** [comment] 2021-05-18 18:34
I like the app, I like the plan to make it more intuitive and I like your new ideas about this. I recommend this app to my students, because it is one of the few free apps that can record single positions and export them into a custom file format. I can confirm that I need to teach them how to use the app in its current state.

They usually use it to record single positions rather than tracking. That's why I am focused on the "Annotate" feature. I'm not sure if the word Annotate is intuitive enough for the users to understand its function. It creates a new point in the database and you can add a description. I'm sorry, I don't have a perfect suggestion, but maybe something like "(Record) sinlge position/point" would describe it better. But I guess this is too long... Or maybe just "Waypoint"? This is at least the nomenclature used in GPX files: Waypoints (= single points) vs. Trackpoints (= points that form the track). But I know this can still be misleading to people who are not used to these terms... (BTW: This is a bit confusing in the current German version, because Trackpoints is translated with Wegpunkte, which is a literal translation of Waypoints.)

Also: Will the Record button say "Record track" or only "Record"? I don't know if it is enough to say only "Record", but on the other hand the app is called "Logger", so maybe it is enough and the "Annotate" feature for single points is just an additional thing and not equally important. At least for me it is not obvious if "Record" records a single point or if tracking starts.

A different idea: Use the bottom bar only for tracking-related buttons (Start/Pause, Stop, Lock) and use another bar for recording single points. I don't know if the free space is intended for something else. If so, stay on the same bar, but clearly separate the "Annotate" button from the rest by using a frame or a different color. I think the two functions are so different from each other that their buttons should not be mixed.

Suggestion with two separate bars looking something like this (I used GIMP):

![grafik](https://user-images.githubusercontent.com/20191135/118703781-c3e09a00-b816-11eb-84ca-8bbe01e44833.png)

![grafik](https://user-images.githubusercontent.com/20191135/118703819-cc38d500-b816-11eb-8ce7-bea4a8789050.png)

**Comment by GrazianoCapelli** [comment] 2021-05-22 09:28
I would write here the thoughts behind the new incoming interface:

Basing on the user's feedback, the past month we rethought from scratch the bottom bar in order to make the app more user friendly for the new users. The new bottom bar is strongly inspired by the audio recorders, with the hope to give to the users an interface they are used to.

When the app starts, only 3 buttons are active:

![NO_POINTS_bar](https://user-images.githubusercontent.com/6907566/119219594-97fb3800-bae6-11eb-952d-3a34521dc76a.jpg)
1) Among them, the **Record** one should suggests (like audio recorders) to be the button that starts a (continuous) acquisition of ~~audio~~ GPS points;
2) The **Annotate** button (with the icon that represent a placemark), should suggest the single action to take an annotation (or to add a placemark);
3) The **Lock** button's function could be not immediately clear; but clicking on it, a toast with the text "The bottom bar is locked" makes it clearer.

In general I think that _less is better_:
if the user can do 2 actions, then a good interface should provide only 2 buttons.

Regarding the text, we must use something short that refers to actions, in order to make clear from beginning that the widget is an actionbar, and not the tab container for the tabbed interface (that is at the top).
If the use of the words "Record", "Pause", and "Stop" has been simple, the string for the placemark button required a bit more research. The choice fell on "Annotate" basing on other apps, on the fact that some translators already translated the word _Placemark_ as _Annotation_ in their localisations, and on the feedback about the possible confusion between _Placemarks_ and _Trackpoints_ in german language.

Any idea about the "Annotate" string is welcome.

_I take this opportunity to link the GPS Logger's localisation page, when anyone can contribute with translations and proofreading:
https://crowdin.com/project/gpslogger
In few days we'll published the new strings to translate for the incoming v3.0.0._

Regarding the position of the buttons, for layout reason we have to put the Record/Pause and the Annotate buttons (that show the amount of points and annotation above) on the right part of the screen: in fact, when there is enough space, the app shows the satellites and the time of the fix and, in case of horizontal orientation, it shows them on the left, immediately above the bottom bar. If the numbers of Trackpoints/Annotation are on the left side, it could cause a possible overlapping.

Unfortunately it is not possible at this time to evaluate something radically different like the double heighted bar @Turdus suggested, because it should require a new discussion (for example we should start to discuss the "Play" button, that could suggest a playback of the recorded track, like a "Drive me back" feature) and - ad the end of the discussion - a complete revisiting of the app's layout.

_I take this opoprtunity to thank all the people that posted here (and also using email or a Play Store review) suggestion, ideas, and constructive criticism: if the new bar will be better than the old one, most of the credit goes to them._

In my opinion, at this stage of developing, we should first try the new bottom bar approach (that I consider better than the old), with the purpose to collect user's feedback in the next months.
We leave this issue open in order to gather feedbacks and ideas for the next versions.

Of course we'll be very glad to receive feedbacks, specially about @Turdus 's students: we hope that the new interface will start to shorten the getting started teaching!

**Comment by TVEgit** [comment] 2021-06-03 10:18
Hello. I'm new to this tool and recently contributed to French translation on Crowdin as TVE1964. **Loving it!**
I strongly endorse this new bottom bar evolution.
My contribution: I would much prefer the term "**_Mark_**" rather than "Annotate".
_Mark_ is both a verb and a noun. "_Mark_" is close to "_placemark_", an intuitive word but also a much used synonym to waypoint. WPT is the tag used in GPX file format so it becomes widely known but I believe "_Mark_" alongside "_Record_", especially  with the pin icon, should be very self explanatory.

For another discussion/feature, I think a list of "Marks" (or Annotations) would be nice, with a possibility to delete some (it can be quite normal to do this "on the field".

**Comment by GrazianoCapelli** [comment] 2021-06-04 19:50
When we chosen Annotation we look at some apps on the store, and we found that it is often used to name the Placemark.
In effect the term "Mark" could be a good alternative to "Annotation", in fact some translators already translated it this way; we could start with the source string **Annotation** in order to collect some feedbacks (the app is going to be released very soon) and, in case, we could switch to "Mark" on v3.0.1.
Anyway, feel free to translate it as "Mark" in French localization.

You could propose it on our Translation & Proofreading Channel (#16)

Regarding the Annotation list, I think it would be a great idea (we are already thinking to implement it in the future): you could start by opening a new issue in order to keep track of it, collect ideas, mock-ups and proposals from users.

**Comment by pastacolsugo** [comment] 2021-06-05 23:13
Hello Graziano and other contributors,
I've been using the app for about a year now and I really like it, it does what I need, nothing more and it's open source.
I confirm once again the interface it's not very intuitive as is and I'm happy to read there are improvements in the works.
The real shortcoming is the inability to rename tracks, but it's clear its one of the next steps after the bottom bar update.

Coming to the bottom bar and the UX discussion that's in progress I would like to point out that the UI-mock-screenshot I've seen here are focused on the "GPS Fix" tab, while the information that's been discussed like the number of Points and Annotations is something that may be better placed in the "Track" tab, as it's information that's related to the track the user it's recording.

For this coming soon release I would like to emphasize how important it will be to keep the "Stop" button harder to press accidentally. For example I use this app while trekking or mountain biking and would hate to find out that I accidentally stopped the recording mid way. I advise to carefully consider this aspect for this update, as the stop button is now very close to some frequently used functionalities like the "Lock" and "Annotation" buttons, and the target area for the click has also been halved.
I liked the double press requirement for the tick we have been using, but I must admit its physical distance from the other buttons was a well designed feature.

Thanks for your work and this discussion, I'm starting to look into the code and I may submit some pull requests in the future.

**Comment by GrazianoCapelli** [comment] 2021-06-06 07:35
Hello @pastacolsugo,

> The real shortcoming is the inability to rename tracks, but it's clear its one of the next steps after the bottom bar update.

The ability to rename the tracks has been already implemented and will be included on v3.0.0. You can read more about the topic on issue #47.

> Coming to the bottom bar and the UX discussion that's in progress I would like to point out that the UI-mock-screenshot I've seen here are focused on the "GPS Fix" tab, while the information that's been discussed like the number of Points and Annotations is something that may be better placed in the "Track" tab, as it's information that's related to the track the user it's recording.

Regarding the number of Trackpoints, in effect all the screenshots on this issue show the GPS FIX tab.
The numbers at the top of the "Record" and "Annotate" buttons follow the bottom bar, thus they are visible on GPS FIX and TRACK tab.
The TRACK tab with the new interface looks like the screenshot here below:

![Screenshot_20210601-221451_GPS Logger_s](https://user-images.githubusercontent.com/6907566/120914614-a6795000-c69f-11eb-83a5-a36e853f9e27.jpg)

You are right about the natural position of the Trackpoints and Annotations number. As you can see, we added two tiles showing the number of Trackpoints and Annotations (commit 3fd0894).
It is a duplication of information, but the users seems to like the small numbers of Trackpoints on the bottombar as feedback of recording progress, so we chosen to maintain them on the new bottom bar too.

> For this coming soon release I would like to emphasize how important it will be to keep the "Stop" button harder to press accidentally. For example I use this app while trekking or mountain biking and would hate to find out that I accidentally stopped the recording mid way. I advise to carefully consider this aspect for this update, as the stop button is now very close to some frequently used functionalities like the "Lock" and "Annotation" buttons, and the target area for the click has also been halved.
I liked the double press requirement for the tick we have been using, but I must admit its physical distance from the other buttons was a well designed feature.

You hit one of the main topics of interfaces. The past interface placed the button on top in order to avoid accidental clicks, at the cost of intuitiveness. The new one is a step forward on intuitiveness, but we are conscious that is more prone to accidental clicks.
To limit that, we added a "Lock" button to the bar.
Furthermore, if the user clicks the wrong button, the operation is reversible: he can click "Cancel" on finalization dialog and then press "Record" again: It is the exact behaviour of many audio recorders (like @ygoe rightly suggested).

I think we could make the "Stop" button less prone to accidental clicks in 3 ways:
1) Implementing a long click (or a double click) for the "Stop" button, like previously;
2) Stopping the recording when the user press "OK" on the finalization dialog instead of stopping when the user clicks "Stop" (we implemented it this way, but we reverted it because the stop button must act immediately, also if the user does't finalize the track);
3) Placing "Stop" at the left of the bar, to have "Record" and "Annotate" buttons more distant. We could contextually invert "Record" and "Annotate", to match the position of the TRACK's Tiles;

We thought to release the v3.0.0 without any of the precautions above (and start collecting feedbacks), but of course we are not 100% sure that it will be the best approach. At least it comforts us to know that we are following the steps of other recorders.

**Comment by ygoe** [comment] 2021-06-06 17:38
Aren't locks workaround for a flawed UI? What is the real problem why some users accidentially stop their recordings? I mean, that can only happen when the device screen is on, unlocked, the app is active and the device is stored at places that have "fingers" around (or other objects that are equally detected). Usually when I make a track recording, the device is in some pocket where there's no touch things around, and it's off, and it's locked. It would be impossible to stop the recording without me providing my fingerprint or entering the PIN. None of which goes unnoticed, and then the recording still isn't stopped. And if I close the app before turning off the screen, I'd also have to find and switch to the app before anything can happen.

So what is it that happens to you? And do you phone random people and delete stuff just as often on your phones? 😕

**Comment by GrazianoCapelli** [comment] 2021-06-06 18:41
I think @pastacolsugo refers mainly to users that creates Annotations (like for example @Turdus's students) meanwhile recording, because the "Annotate" button is very close to the "Stop" one and it must be clicked when the app is on screen and the bottom bar is unlocked.
We should think the interface for all the possible usages, that could have different needs.
For this reason is important to have several precious points of view to listen and ratiocinate.
Obviously there is no perfect interface, but mediating all the needs we aim to have a quite good interface for everyone.

**Comment by ygoe** [comment] 2021-06-06 18:51
Ah, so it's that the Annotate button might be too close to the Stop button. Then can they be reordered so that nothing that would be regularly used is near the Stop button? Looks like the button bar layout is the main limitation here. It's not able to provide safety distance between critical elements.

**Comment by GrazianoCapelli** [comment] 2021-06-06 19:17
The best order of the elements, for safety, should be something like:
**Annotate - Lock - Record - Stop**, or
**Annotate - Lock - Stop - Record**.

![20210606](https://user-images.githubusercontent.com/6907566/120937054-84b5b280-c70b-11eb-96fc-3284724c3cec.jpg)

The problem is that the buttons with the number above (Annotate and Record) must be placed on the right half, in order to avoid the possible overlapping with tiles. But a possible solution (and very easy to implement) is to limit the tiles visibility in case of overlap.

Another reason I chosen the current implemented layout is that I liked to place the buttons that manage the track close to each other. This way it seems more obvious to think that the stop is referred also to Annotations.

**Comment by ygoe** [comment] 2021-06-06 21:21
What are titles here? This is a strange requirement.

I hope that the Stop button will show a confirmation message before it does its thing? That would probably make the lock feature unnecessary anyway. Otherwise, any layout where Lock and Stop are right next to each other can be considered unsafe in this regard. And if you find a "safe" layout, there would be no need for a lock anymore, right? I'm still puzzled.

**Comment by GrazianoCapelli** [comment] 2021-06-10 11:23
The tiles are the panes that contain data.
On the image below, for example, there is space for extra tiles on the horizontal layout. As result _Max Speed_ and _Altitude Gap_ tiles are very close to the bottom bar.

![Tiles - 20210610](https://user-images.githubusercontent.com/6907566/121515744-d0a77680-c9ed-11eb-902c-274614996a37.jpg)

In Track tab the tiles that are hidden if there is no space are _Annotations_ and _Trackpoints_.
In GPS Fix the extra tiles are _Time_ and _Satellites_.

**Comment by ygoe** [comment] 2021-06-10 11:29
I'm missing a holistic concept here. This looks all a bit hacked together.

**Comment by GrazianoCapelli** [comment] 2021-07-05 10:37
The new bottom bar has been implemented on v3.0.0.
We already received several good feedbacks about it, thus I can definitively consider the new implementation as a step forward.
Time to close the issue.

Of course, we would be glad to receive feedbacks here, specially from partecipants (also if the issue is closed), and to reopen the issue in case of needs.

Anyway, thanks again for your precious collaboration!

**Closed by GrazianoCapelli** 2021-07-05 10:37 UTC
Labels: discuss, feature
